- name: "Configure load balancer"
  hosts: localhost
  tasks:
    - name: Create target group
      community.aws.elb_target_group:
        name: "{{username}}-webserver-group"
        protocol: http
        port: 80
        vpc_id: "{{ aws.vpc_id }}"
        state: present

    - name: Create one target per webserver VM
      community.aws.elb_target:
        target_group_name: "{{username}}-webserver-group"
        target_id: "{{ instance['instance_id'] }}"
        state: present
      vars:
        instance: "{{ hostvars[item] }}"
      loop: "{{ groups['webservers'] }}"

    - name: Establish AWS load balancer
      community.aws.elb_network_lb:
        name: "{{ username }}-webserver-lb"
        subnets:
          - "{{ aws.subnet_id }}"
        listeners:
          - Protocol: TCP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupName: "{{ username }}-webserver-group"
        state: present
