- name: "Configure load balancer"
  hosts: localhost
  tasks:
    - name: Create one target per webserver VM
      community.aws.elb_target:
        target_group_name: "{{academy_user}}-webserver-group"
        target_id: "{{ instance['instance_id'] }}"
        state: present
        region: "{{ aws.region }}"
      vars:
        instance: "{{ hostvars[item] }}"
      loop: "{{ groups['webservers'] }}"

    - name: Wait until the application can be accessed
      uri:
        url: "http://{{academy_user}}.{{aws.hosted_zone}}"
      register: url
      until: url.status == 200
      delay: 10
      retries: 100

    - debug:
        msg: "Your web application can be accessed here: http://{{ academy_user }}.{{ aws.hosted_zone }}"
