- name: "{{ academy_user }} - provision virtual machine"
  hosts: localhost
  gather_facts: false
  tasks:
    - debug: var=academy_user

    - name: Deploy AWS CloudFormation stack
      shell: 'echo "Hello world"'
