- name: "Provision virtual machine"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "{{ academy_user }} - provision virtual machine"
      amazon.aws.cloudformation:
        stack_name: "{{ academy_user }}-stack"
        state: present
        region: '{{ aws_region }}"
        disable_rollback: true
        template: "files/uservm-stack.yml"
        template_parameters:
          SubnetId: "{{ aws.subnet }}"
          SecurityGroupId: "{{ aws.securitygroup }}"
        tags:
          User: "{{ academy_user }}"
          Name: "{{ academy_user }}-vm"
