- name: "Provision virtual machine"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "{{ academy_user }} - provision virtual machine to Amazon Web Services"
      shell: 'echo "Hello world"'
