- name: "Provision virtual machines"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "{{ academy_user }} - provision virtual machine"
      amazon.aws.ec2_instance:
        name: "{{ academy_user }}-vm-{{item}}"
        tags:
          User: "{{ academy_user }}"
        vpc_subnet_id: "{{ aws.subnet }}"
        instance_type: "t2.medium"
        region: "{{ aws.region }}"
        image_id: "{{ aws.ami }}"
        wait: true
        key_name: 'workshop-key-user'
        network:
          assign_public_ip: true
        security_group: "{{ aws.securitygroup }}"
        state: running
      loop:
        - 1
        - 2
