- name: "Provision virtual machine"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "{{ academy_user }} - provision virtual machine"
      amazon.aws.ec2_instance:
        name: "{{ academy_user }}-vm"
        tags:
          User: "{{ academy_user }}"
        vpc_subnet_id: "{{ aws.subnet }}"
        instance_type: "t2.micro"
        region: "{{ aws.region }}"
        image_id: "{{ aws.ami }}"
        wait: true
        network:
          assign_public_ip: true
          groups:
            - "{{ aws.securitygroup }}"
