- name: "Destroy environment"
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/community.aws.aws:
      region: "{{ aws.region }}"
    group/amazon.aws.aws:
      region: "{{ aws.region }}"
  tasks:
    - name: "{{ academy_user }} - destroy virtual machines"
      amazon.aws.ec2_instance:
        state: absent
        wait: true
        filters:
          'tag:User': '{{ academy_user }}'

    - name: "{{ academy_user }} - destroy elb target group"
      community.aws.elb_target_group:
        name: "{{academy_user}}-webserver-group"
        state: absent

    - name: "{{ academy_user }} - destroy elb"
      community.aws.elb_application_lb:
        name: "{{ academy_user }}-webserver-lb"
        state: absent

    - name: "{{ academy_user }} - destroy Route53 record"
      community.aws.route53:
        record: "{{ academy_user }}.{{ aws.hosted_zone }}"
        zone: "{{ aws.hosted_zone }}"
        state: absent
