- name: "Destroy environment"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "{{ academy_user }} - destroy virtual machines"
      amazon.aws.ec2_instance:
        state: absent
        region: "{{ aws.region }}"
        filters:
          'tag:User': '{{ academy_user }}'

    - name: Remove targets from target group for ELB
      community.aws.elb_target_group:
        name: "{{academy_user}}-webserver-group"
        targets: []
        protocol: http
        port: 80
        vpc_id: "{{ aws.vpc_id }}"
        modify_targets: True
        state: present
        region: "{{ aws.region }}"
