- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - fail:
        msg: "AWS credentials missing."
      when:
        - "lookup('env', item) == ''"
      loop:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_REGION

    - name: Create Academy keypair
      amazon.aws.ec2_key:
        name: AcademyKey
      register: academy_key

    - when:
        - "'key pair created' in academy_key.msg"
      name: dump key to tempfile
      copy:
        dest: "academy.key"
        content: "{{ academy_key.key.private_key }}"

    - name: deploy Academy stack
      amazon.aws.cloudformation:
        stack_name: 'AnsibleAcademy'
        state: present
        disable_rollback: true
        template: "files/academy-stack.yaml"
        tags:
          Stack: 'AnsibleAcademy'
      register: stack

    - set_fact:
        vpc_id: "{{ stack.stack_outputs.VpcId }}"
        subnet_id: "{{ stack.stack_outputs.SubnetId }}"
        securitygroup_id: "{{ stack.stack_outputs.SecurityGroupId }}"

    - include_tasks: tasks/configure-aap.yml
